version: '3.8'

services:
  token:
    container_name: token
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run start:token
    ports:
      - 3002:3002
    environment:
      NODE_ENV: 'development'
      PORT: 3002
    # networks:
    #   - corp
    restart: on-failure
  customer:
    container_name: customer
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run start:customer
    ports:
      - 3001:3001
    environment:
      NODE_ENV: 'development'

      PORT: 3001
    # networks:
    #   - corp
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run start:gateway
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'development'
      PORT: 3000
    depends_on:
      - token
      - customer
    # networks:
    #   - corp
    restart: on-failure
volumes:
  mono-node-modules: null

networks:
  corp:
