version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./
      # cache_from:
      #   - i-bank:nx-base
      dockerfile: ./apps/api-gateway/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: api-gateway:nx-base
    ports:
      - 8000:4939
    environment:
      NODE_ENV: "development"
      PORT: 8000
    networks:
      - corp
    restart: on-failure

